from headers import *
im1 = io.imread('testing/mask/image10.png')
im2 = io.imread('testing/model/image10.jpg')
im3 = io.imread('results/image_10_0.5.png')
im4 = io.imread('results/image_10_1.png')
im5 = io.imread('results/image_10_1.5.png')
im6 = io.imread('results/image_10_2.0.png')

fig, xs = plt.subplots(2, 3)
xs[0][0].imshow(im1, cmap="gray")
xs[0][0].set_title("Mask")
xs[0][0].axis('off')
xs[0][1].imshow(im2, cmap="gray")
xs[0][1].set_title("Image")
xs[0][1].axis('off')
xs[0][2].imshow(im3, cmap="gray")
xs[0][2].set_title("phi=0.5")
xs[0][2].axis('off')
xs[1][0].imshow(im4, cmap="gray")
xs[1][0].set_title("phi=1")
xs[1][0].axis('off')
xs[1][1].imshow(im5, cmap="gray")
xs[1][1].set_title("phi=1.5")
xs[1][1].axis('off')
xs[1][2].imshow(im6, cmap="gray")
xs[1][2].set_title("phi=2")
xs[1][2].axis('off')
plt.show()
